<?php

use CWP\Search\Solr\CwpSolrIndex;

class SearchIndex extends CwpSolrIndex
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

//    protected function getStoredDefault()
//    {
//       return 'false';
//    }
}