<?php

use CWP\Search\Solr\CwpSolrIndex;

class SearchIndex extends CwpSolrIndex
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->addStoredField('Title');
        $this->addStoredField('MenuTitle');
        $this->addStoredField('Content');
        $this->addStoredField('MetaDescription');
        $this->addStoredField('ExtraMeta');
    }

//    protected function getStoredDefault()
//    {
//       return 'false';
//    }
}